# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
import numpy as np

In [6]:
a1=np.arange(10,51)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
a2=np.arange(10,51,2)
a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
m=np.array([[0,1,2],[3,4,5],[6,7,8]])
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1 using seed 10

In [10]:
np.random.seed(10)
a4=np.random.uniform(0,1)
a4

0.771320643266746

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution using seed 1

In [11]:
np.random.seed(0)
a5=np.random.normal(0,1,25)
a5

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574,
       -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462])

#### Create the following matrix from 25 random numbers using seed 0:

In [12]:
np.random.seed(0)
a6=np.random.rand(5,5)
a6

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

Create this below matrix (mat)?

In [14]:
mat=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Make the below subset from the above matrix called mat?

In [15]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Fetch the element 20 from mat

In [16]:
mat[3,4]

20

Fetch the below sub-array from mat

In [52]:
mat[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

Fetch the below sub-array from mat

In [18]:
mat[4:,:]

array([[21, 22, 23, 24, 25]])

Fetch the below sub-array from mat

In [19]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [20]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [21]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [22]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

Write a function ('Grade') that takes external input of scores/marks in a loop for 6 times. Then it prints "Grade A" if marks>80, "Grade B" if marks between (60,80), "Grade C" if marks between (40,60) and "Grade D" for below 40. Then call the function to check the grades for 35,45,65,75 & 85

In [24]:
for i in range(6):
    grade=int(input("Enter Marks: "))
    if grade>80:
        print("Grade A")
    elif 60<grade<80:
        print("Grade B")
    elif 40<grade<60:
        print("Grade C")
    else:
        print("Grade D")
        

Enter Marks: 35
Grade D
Enter Marks: 45
Grade C
Enter Marks: 75
Grade B
Enter Marks: 80
Grade D
Enter Marks: 95
Grade A
Enter Marks: 100
Grade A


Write a function which take simulation number (n) as argument, and do the following:  
- generate `n` random numbers from normal distribution with mean 10 and sigma 2. Use `np.random.normal()` method 
- Calculate sample mean(m) and sample standard deviation(s)
- Calculate percentage of values lying within mean+/-sigma, mean+/-2xsigma, mean+/-3xsigma, and outside mean+/-3xsigma
- produce the result for n=500,1000,5000,10000  

Try to put the above progrm in a user defined function with argument as `n`

In [33]:
a=np.random.normal(10,2,500)
a

array([13.47572651, 11.12974062,  9.70755994, 11.95664555,  7.32913447,
        8.07484902,  9.56959865, 11.22683274,  7.39817298, 11.80306006,
       10.00574182,  8.13260717, 10.3875766 , 11.38261728, 11.30072769,
        7.92392612,  8.52994498, 12.20099802, 13.72786182, 11.21308419,
       10.75906985,  9.92285613,  9.85604865,  7.24608584,  8.94288591,
        7.137814  , 11.93656564,  9.65493385,  8.09410218, 13.94437966,
       12.36622144,  7.80661355, 12.08334548,  9.9764971 ,  9.46330075,
       11.60428149,  6.71074195, 10.87543116,  9.13976865, 12.14164874,
        6.92826918,  8.35849722,  9.78087294,  6.0060186 ,  8.05168502,
        7.32575307,  9.49068339, 10.01222676, 13.19875847,  8.90330199,
        8.17241845,  7.82309807, 11.47730532,  9.22873238, 10.67466205,
        7.03868359, 12.33951601,  8.55774223,  9.73853657, 10.93848095,
        9.14502287, 10.41925186, 11.45605875,  5.64698608, 11.62806048,
        7.42137312, 13.477759  , 10.87156013, 11.30972754,  5.84

___Application of Central Limit Theorem___  
- generate 30 integers from a poisson distribution with lambda `5.5`. Use `np.random.poisson(lambda,size)` method
- find mean(m)
- repeat this process 5000 times  
- calculate mean(mu) and std(sig) of these 5000 values 
- check the proportion of values between `mu(+/-)k*sig` for k=1,2,3


In [39]:
from numpy import mean
G=np.random.poisson(5.5,30)
print(G)
print('The mean is {}'.format(mean(G)))

[4 6 5 3 7 5 4 5 6 7 4 7 8 2 2 8 6 4 4 5 1 1 2 6 6 7 6 4 4 5]
The mean is 4.8


In [51]:
from numpy import std
means=[mean(np.random.poisson(5.5,30)) for _i in range(5000)]
stds=[std(np.random.poisson(5.5,30)) for i in range(5000)]
print('The mean of sample means is {}'.format(mean(means)))
print('The std is {}'.format(std(stds)))

The mean of sample means is 5.51236
The std is 0.3153136100987933


In [61]:
mu=means
sig=stds
def prop:
    if i in mu-sig<i<mu+sig:
        print(prop in mu-sig<i<mu+sig )
    if i in mu-2*sig<i<mu+2*sig:
        print(prop in  mu-2*sig<i<mu+2*sig)
    if i in mu-3*sig<i<mu+3*sig:
        print(prop in mu-3*sig<i<mu+3*sig)


    

SyntaxError: invalid syntax (<ipython-input-61-fc336a380460>, line 1)

# Thank You !